services:

  # ── Next.js App ──────────────────────────────────────────────────────────────
  app:
    build:
      context: ./wa-api
      dockerfile: Dockerfile
    container_name: wa-api-web
    env_file:
      - ./wa-api/.env
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: unless-stopped