import { PricingPageData } from "@/types/Pricing";

export const PRICING_DATA: PricingPageData = {
  plans: [
    {
      id: "free",
      name: "Free",
      monthlyUSD: 0,
      messages: 100,
      messagesLabel: "100 msgs / mo",
      description: "Try it out, no strings attached",
      cta: "Get Started Free",
      highlighted: false,
      badge: null,
    },
    {
      id: "starter",
      name: "Starter",
      monthlyUSD: 19,
      messages: 2000,
      messagesLabel: "2,000 msgs / mo",
      description: "Perfect for solo founders and small teams",
      cta: "Start Now",
      highlighted: false,
      badge: null,
    },
    {
      id: "growth",
      name: "Growth",
      monthlyUSD: 49,
      messages: 6000,
      messagesLabel: "6,000 msgs / mo",
      description: "The sweet spot for growing businesses",
      cta: "Get Growth",
      highlighted: true,
      badge: "Most Popular ⭐",
    },
    {
      id: "pro",
      name: "Pro",
      monthlyUSD: 99,
      messages: 15000,
      messagesLabel: "15,000 msgs / mo",
      description: "For power users with high engagement",
      cta: "Go Pro",
      highlighted: false,
      badge: null,
    },
    {
      id: "enterprise",
      name: "Enterprise",
      monthlyUSD: null,
      messages: null,
      messagesLabel: "Unlimited msgs",
      description: "Custom volume, SLA, and dedicated support",
      cta: "Contact Sales",
      highlighted: false,
      badge: "Custom",
    },
  ],
  currencies: {
    USD: { symbol: "$", name: "US Dollar", rate: 1 },
    EUR: { symbol: "€", name: "Euro", rate: 0.93 },
    GBP: { symbol: "£", name: "British Pound", rate: 0.79 },
    INR: { symbol: "₹", name: "Indian Rupee", rate: 94.7 },
  },
  yearlyDiscount: 0.2,
  supportedCurrencies: ["USD", "EUR", "GBP", "INR"],
  allFeatures: [
    { icon: "🤖", label: "AI Assistant (24/7 smart replies)" },
    { icon: "🧠", label: "AI Agent (autonomous workflows)" },
    { icon: "📢", label: "Unlimited broadcast campaigns" },
    { icon: "👥", label: "Unlimited contacts" },
    { icon: "📊", label: "Advanced analytics dashboard" },
    { icon: "🔌", label: "Full API access" },
    { icon: "📱", label: "WhatsApp Business API integration" },
    { icon: "🎨", label: "Custom message templates" },
    { icon: "🔒", label: "Advanced security features" },
    { icon: "📞", label: "Priority support" },
  ],
  featureBreakdown: [
    {
      icon: "🤖",
      title: "AI Assistant",
      desc: "24/7 intelligent auto-replies that understand context and resolve queries instantly.",
    },
    {
      icon: "🧠",
      title: "AI Agent",
      desc: "Autonomous multi-step workflows — book appointments, qualify leads, process orders.",
    },
    {
      icon: "📢",
      title: "Unlimited Broadcasts",
      desc: "Send campaigns to your entire contact list with no cap on recipients or frequency.",
    },
    {
      icon: "👥",
      title: "Unlimited Contacts",
      desc: "Import, segment, and manage as many contacts as you need — forever free of charge.",
    },
    {
      icon: "📊",
      title: "Advanced Analytics",
      desc: "Delivery rates, read receipts, reply rates, campaign ROI — full visibility.",
    },
    {
      icon: "🔌",
      title: "Full API Access",
      desc: "REST API, webhooks, and WhatsApp Business API integration on every tier.",
    },
    {
      icon: "🎨",
      title: "Custom Templates",
      desc: "Build rich media message templates: text, images, buttons, and quick replies.",
    },
    {
      icon: "📱",
      title: "Multiple WA Numbers",
      desc: "Connect multiple WhatsApp Business numbers under one account.",
    },
    {
      icon: "🔒",
      title: "Security & Compliance",
      desc: "End-to-end encrypted delivery, audit logs, and role-based access controls.",
    },
  ],
  faqs: [
    {
      q: "Are all features available on every plan?",
      a: "Yes! Every plan — including Free — includes our full feature set: AI Assistant, AI Agent, unlimited contacts, unlimited broadcasts, API access, and analytics. The only difference between plans is the number of messages included per month.",
    },
    {
      q: "What happens when I exceed my monthly message limit?",
      a: "When you reach your plan's message limit, you can either upgrade to the next plan or purchase additional messages at our standard rate. We'll notify you at 80% and 100% usage so you're never caught off guard.",
    },
    {
      q: "What are Facebook (Meta) API charges?",
      a: "Facebook's WhatsApp Business API charges are separate and billed directly by Meta to your Facebook Business Manager account. Our plan fees cover platform usage only. Meta charges vary by conversation type (utility, marketing, authentication) and region.",
    },
    {
      q: "How does the 20% yearly discount work?",
      a: "Switch to annual billing and pay for 10 months instead of 12 — that's 2 months free. The discount applies immediately and your plan renews annually at the discounted rate.",
    },
    {
      q: "Can I switch plans anytime?",
      a: "Absolutely. Upgrade or downgrade at any time. Upgrades take effect immediately; downgrades apply at the next billing cycle.",
    },
    {
      q: "Is there a free trial for paid plans?",
      a: "Our Free plan gives you 100 messages/month forever so you can test the platform before committing. No credit card required.",
    },
  ],
  metaPricingUrl: "https://whatsappbusiness.com/products/platform-pricing/",
};
